[2023-09-02T06:44:14.533+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls permission to 509
[2023-09-02T06:44:14.534+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls'
[2023-09-02T06:44:14.562+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls permission to 509
[2023-09-02T06:44:14.563+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls'
[2023-09-02T06:44:14.585+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.remove_nulls manual__2023-09-02T06:43:15.061347+00:00 [queued]>
[2023-09-02T06:44:14.595+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.remove_nulls manual__2023-09-02T06:43:15.061347+00:00 [queued]>
[2023-09-02T06:44:14.595+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-09-02T06:44:14.607+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): remove_nulls> on 2023-09-02 06:43:15.061347+00:00
[2023-09-02T06:44:14.613+0000] {standard_task_runner.py:57} INFO - Started process 4165 to run task
[2023-09-02T06:44:14.615+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'remove_nulls', 'manual__2023-09-02T06:43:15.061347+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmp2yu8667a']
[2023-09-02T06:44:14.617+0000] {standard_task_runner.py:85} INFO - Job 130: Subtask remove_nulls
[2023-09-02T06:44:14.654+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls permission to 509
[2023-09-02T06:44:14.655+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-02T06:43:15.061347+00:00/task_id=remove_nulls'
[2023-09-02T06:44:14.657+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.remove_nulls manual__2023-09-02T06:43:15.061347+00:00 [running]> on host 1a0e8b05e04d
[2023-09-02T06:44:14.724+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='remove_nulls' AIRFLOW_CTX_EXECUTION_DATE='2023-09-02T06:43:15.061347+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-02T06:43:15.061347+00:00'
[2023-09-02T06:44:14.727+0000] {bigquery.py:1234} INFO - Executing: DELETE autotrader-toyota-dashboard.autotrader_staging.listings_raw
        WHERE
        NOT EXISTS (
        SELECT
        *
        FROM
        autotrader-toyota-dashboard.autotrader_staging.listings_raw
        WHERE
        NOT ( price IS NULL
        OR odometer IS NULL
        OR year IS NULL
        OR MODEL IS NULL
        OR type IS NULL
        OR suburb IS NULL
        OR state IS NULL 
        ));
[2023-09-02T06:44:14.736+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-09-02T06:44:14.739+0000] {base.py:73} INFO - Using connection ID 'google_cloud' for task execution.
[2023-09-02T06:44:14.745+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2109 AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2023-09-02T06:44:14.781+0000] {bigquery.py:1596} INFO - Inserting job ***_1693637054781221_6d5a48f03720470b45c45edc759730c5
[2023-09-02T06:44:15.704+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1242, in execute
    self.job_id = self.hook.run_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2244, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 467, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1602, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Encountered " "DELETE" "DELETE "" at line 1, column 1.
Was expecting:
    <EOF>
[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]

Location: asia-southeast1
Job ID: airflow_1693637054781221_6d5a48f03720470b45c45edc759730c5

[2023-09-02T06:44:15.715+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Autotrader_ETL_DAG, task_id=remove_nulls, execution_date=20230902T064315, start_date=20230902T064414, end_date=20230902T064415
[2023-09-02T06:44:15.727+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 130 for task remove_nulls (400 Encountered " "DELETE" "DELETE "" at line 1, column 1.
Was expecting:
    <EOF>
[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]

Location: asia-southeast1
Job ID: airflow_1693637054781221_6d5a48f03720470b45c45edc759730c5
; 4165)
[2023-09-02T06:44:15.754+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-02T06:44:15.776+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
