[2023-09-05T00:40:45.989+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int permission to 509
[2023-09-05T00:40:45.990+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int'
[2023-09-05T00:40:46.022+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int permission to 509
[2023-09-05T00:40:46.023+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int'
[2023-09-05T00:40:46.048+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.string_to_int manual__2023-09-05T00:37:22.901541+00:00 [queued]>
[2023-09-05T00:40:46.057+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.string_to_int manual__2023-09-05T00:37:22.901541+00:00 [queued]>
[2023-09-05T00:40:46.057+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-09-05T00:40:46.071+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): string_to_int> on 2023-09-05 00:37:22.901541+00:00
[2023-09-05T00:40:46.079+0000] {standard_task_runner.py:57} INFO - Started process 361 to run task
[2023-09-05T00:40:46.081+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'string_to_int', 'manual__2023-09-05T00:37:22.901541+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmpr6u6zp0a']
[2023-09-05T00:40:46.084+0000] {standard_task_runner.py:85} INFO - Job 392: Subtask string_to_int
[2023-09-05T00:40:46.139+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int permission to 509
[2023-09-05T00:40:46.140+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-05T00:37:22.901541+00:00/task_id=string_to_int'
[2023-09-05T00:40:46.143+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.string_to_int manual__2023-09-05T00:37:22.901541+00:00 [running]> on host 412bb32711f9
[2023-09-05T00:40:46.219+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='string_to_int' AIRFLOW_CTX_EXECUTION_DATE='2023-09-05T00:37:22.901541+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-05T00:37:22.901541+00:00'
[2023-09-05T00:40:46.221+0000] {bigquery.py:1234} INFO - Executing: CREATE OR REPLACE TABLE autotrader-toyota-dashboard.autotrader_staging.listings_raw AS
        SELECT
        CAST(price as INT64) as price,
        CAST(odometer as INT64) as odometer,
        CAST(year as INT64) as year,
        model,
        type,
        suburb,
        state
        FROM autotrader-toyota-dashboard.autotrader_staging.listings_raw;
[2023-09-05T00:40:46.230+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-09-05T00:40:46.235+0000] {base.py:73} INFO - Using connection ID 'google_cloud' for task execution.
[2023-09-05T00:40:46.240+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2109 AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2023-09-05T00:40:46.285+0000] {bigquery.py:1596} INFO - Inserting job ***_1693874446285116_c8ce97df58ed84f72be942b0a26c5a72
[2023-09-05T00:40:47.653+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1242, in execute
    self.job_id = self.hook.run_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2244, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 467, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1602, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Bad int64 value: 

Location: asia-southeast1
Job ID: airflow_1693874446285116_c8ce97df58ed84f72be942b0a26c5a72

[2023-09-05T00:40:47.668+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Autotrader_ETL_DAG, task_id=string_to_int, execution_date=20230905T003722, start_date=20230905T004046, end_date=20230905T004047
[2023-09-05T00:40:47.683+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 392 for task string_to_int (400 Bad int64 value: 

Location: asia-southeast1
Job ID: airflow_1693874446285116_c8ce97df58ed84f72be942b0a26c5a72
; 361)
[2023-09-05T00:40:47.700+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-05T00:40:47.729+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
