[2023-09-07T06:34:32.412+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim permission to 509
[2023-09-07T06:34:32.413+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim'
[2023-09-07T06:34:32.440+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim permission to 509
[2023-09-07T06:34:32.441+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim'
[2023-09-07T06:34:32.463+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.insert_into_location_dim manual__2023-09-07T06:32:15.448537+00:00 [queued]>
[2023-09-07T06:34:32.472+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.insert_into_location_dim manual__2023-09-07T06:32:15.448537+00:00 [queued]>
[2023-09-07T06:34:32.473+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-09-07T06:34:32.490+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): insert_into_location_dim> on 2023-09-07 06:32:15.448537+00:00
[2023-09-07T06:34:32.497+0000] {standard_task_runner.py:57} INFO - Started process 351 to run task
[2023-09-07T06:34:32.499+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'insert_into_location_dim', 'manual__2023-09-07T06:32:15.448537+00:00', '--job-id', '476', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmp_9zkrdi8']
[2023-09-07T06:34:32.501+0000] {standard_task_runner.py:85} INFO - Job 476: Subtask insert_into_location_dim
[2023-09-07T06:34:32.538+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim permission to 509
[2023-09-07T06:34:32.538+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-07T06:32:15.448537+00:00/task_id=insert_into_location_dim'
[2023-09-07T06:34:32.541+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.insert_into_location_dim manual__2023-09-07T06:32:15.448537+00:00 [running]> on host 412bb32711f9
[2023-09-07T06:34:32.605+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_into_location_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-09-07T06:32:15.448537+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-07T06:32:15.448537+00:00'
[2023-09-07T06:34:32.608+0000] {bigquery.py:1234} INFO - Executing: INSERT INTO autotrader-toyota-dashboard.autotrader_transformed.location_dim (location_key, suburb, state)
        SELECT
        ROW_NUMBER() OVER () as location_key,
        suburb,
        state
        FROM (
        SELECT 
        DISTINCT
        suburb,
        state
        FROM
        autotrader-toyota-dashboard.autotrader_staging.listings_raw
        );
[2023-09-07T06:34:32.617+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-09-07T06:34:32.621+0000] {base.py:73} INFO - Using connection ID 'google_cloud' for task execution.
[2023-09-07T06:34:32.627+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2109 AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2023-09-07T06:34:32.663+0000] {bigquery.py:1596} INFO - Inserting job ***_1694068472663039_945dcafba0ba8e574853943552db7aa1
[2023-09-07T06:34:36.110+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Autotrader_ETL_DAG, task_id=insert_into_location_dim, execution_date=20230907T063215, start_date=20230907T063432, end_date=20230907T063436
[2023-09-07T06:34:36.133+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-07T06:34:36.156+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
