[2023-09-09T05:28:03.845+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table permission to 509
[2023-09-09T05:28:03.846+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table'
[2023-09-09T05:28:03.900+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table permission to 509
[2023-09-09T05:28:03.901+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table'
[2023-09-09T05:28:03.940+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.insert_csv_data_into_australian_suburbs_table manual__2023-09-09T05:25:05.156268+00:00 [queued]>
[2023-09-09T05:28:03.953+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.insert_csv_data_into_australian_suburbs_table manual__2023-09-09T05:25:05.156268+00:00 [queued]>
[2023-09-09T05:28:03.954+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-09-09T05:28:03.975+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): insert_csv_data_into_australian_suburbs_table> on 2023-09-09 05:25:05.156268+00:00
[2023-09-09T05:28:03.984+0000] {standard_task_runner.py:57} INFO - Started process 3718 to run task
[2023-09-09T05:28:03.989+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'insert_csv_data_into_australian_suburbs_table', 'manual__2023-09-09T05:25:05.156268+00:00', '--job-id', '502', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmpaamyzn7l']
[2023-09-09T05:28:03.992+0000] {standard_task_runner.py:85} INFO - Job 502: Subtask insert_csv_data_into_australian_suburbs_table
[2023-09-09T05:28:04.063+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table permission to 509
[2023-09-09T05:28:04.065+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-09T05:25:05.156268+00:00/task_id=insert_csv_data_into_australian_suburbs_table'
[2023-09-09T05:28:04.070+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.insert_csv_data_into_australian_suburbs_table manual__2023-09-09T05:25:05.156268+00:00 [running]> on host 412bb32711f9
[2023-09-09T05:28:04.215+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='insert_csv_data_into_australian_suburbs_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-09T05:25:05.156268+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-09T05:25:05.156268+00:00'
[2023-09-09T05:28:04.238+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-09-09T05:28:04.245+0000] {base.py:73} INFO - Using connection ID 'google_cloud' for task execution.
[2023-09-09T05:28:04.247+0000] {gcs_to_bigquery.py:375} INFO - Using existing BigQuery table for storing data...
[2023-09-09T05:28:04.308+0000] {gcs_to_bigquery.py:379} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'autotrader-toyota-dashboard', 'datasetId': 'autotrader_staging', 'tableId': 'australian_suburbs'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://autotrader-raw/australian-suburbs.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'id', 'type': 'INT64'}, {'name': 'suburb', 'type': 'STRING'}, {'name': 'state', 'type': 'STRING'}, {'name': 'latitude', 'type': 'FLOAT64'}, {'name': 'longitude', 'type': 'FLOAT64'}]}, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-09-09T05:28:04.310+0000] {bigquery.py:1596} INFO - Inserting job ***_Autotrader_ETL_DAG_insert_csv_data_into_australian_suburbs_table_2023_09_09T05_25_05_156268_00_00_80df373a03ff5f0923ed5ad3adeedf3f
[2023-09-09T05:28:05.635+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 438, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://autotrader-raw/australian-suburbs.csv
[2023-09-09T05:28:05.652+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Autotrader_ETL_DAG, task_id=insert_csv_data_into_australian_suburbs_table, execution_date=20230909T052505, start_date=20230909T052803, end_date=20230909T052805
[2023-09-09T05:28:05.676+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 502 for task insert_csv_data_into_australian_suburbs_table (404 Not found: URI gs://autotrader-raw/australian-suburbs.csv; 3718)
[2023-09-09T05:28:05.693+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-09T05:28:05.742+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
